# Generated by Django 3.0.2 on 2020-01-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='countryCode2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobileNumber2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
    ]
