# Generated by Django 3.0.2 on 2020-01-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_discount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discount',
            new_name='Offers',
        ),
    ]
